"""PDF report generation service using Jinja2 + WeasyPrint."""

from __future__ import annotations

import io
from datetime import datetime, UTC
from typing import TYPE_CHECKING

import structlog
from jinja2 import Environment, PackageLoader, select_autoescape

logger = structlog.get_logger(__name__)

# Jinja2 environment pointing at templates/ directory
try:
    _jinja_env = Environment(
        loader=PackageLoader("app", "templates"),
        autoescape=select_autoescape(["html"]),
    )
except Exception:
    # Fallback: inline template
    _jinja_env = None


_INLINE_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  body { font-family: 'Helvetica Neue', sans-serif; color: #1a1a2e; margin: 40px; }
  h1 { color: #e94560; font-size: 28px; }
  h2 { color: #16213e; font-size: 18px; border-bottom: 2px solid #e94560; padding-bottom: 6px; }
  .score-badge {
    display: inline-block; padding: 8px 20px; border-radius: 20px;
    font-size: 24px; font-weight: bold; color: white;
    background: {% if scan.risk_score.level == 'critical' %}#e94560{% elif scan.risk_score.level == 'high' %}#f5a623{% elif scan.risk_score.level == 'medium' %}#f8d800{% else %}#4caf50{% endif %};
  }
  .clause { background: #f9f9f9; border-left: 4px solid #e94560; padding: 12px; margin: 10px 0; border-radius: 4px; }
  .label { display: inline-block; background: #e94560; color: white; font-size: 11px; padding: 2px 8px; border-radius: 10px; margin: 2px; }
  .label.clean { background: #4caf50; }
  .meta { color: #888; font-size: 12px; }
  table { width: 100%; border-collapse: collapse; margin-top: 10px; }
  th { background: #16213e; color: white; padding: 8px; text-align: left; }
  td { padding: 8px; border-bottom: 1px solid #eee; }
  tr:nth-child(even) { background: #f9f9f9; }
</style>
</head>
<body>
<h1>🔍 Dark Pattern Detection Report</h1>
<p class="meta">Domain: <strong>{{ scan.domain }}</strong> &nbsp;|&nbsp; Scanned: {{ scan.scanned_at.strftime('%Y-%m-%d %H:%M UTC') }} &nbsp;|&nbsp; Scan ID: {{ scan.scan_id }}</p>

<h2>Overall Risk Score</h2>
<div class="score-badge">{{ scan.risk_score.score }} / 10 &nbsp; ({{ scan.risk_score.level | upper }})</div>
<p>NLP Score: {{ scan.risk_score.nlp_score }} &nbsp;|&nbsp; CV Score: {{ scan.risk_score.cv_score }}</p>

{% if scan.nlp_results %}
<h2>T&C Clause Analysis ({{ scan.nlp_results | length }} clauses)</h2>
{% for clause in scan.nlp_results %}
{% if clause.severity > 0.1 %}
<div class="clause">
  <p>{{ clause.text }}</p>
  {% for lbl in clause.labels %}
  <span class="label {{ 'clean' if lbl == 'clean' }}">{{ lbl }}</span>
  {% endfor %}
  <br><small class="meta">Severity: {{ "%.2f"|format(clause.severity) }} &nbsp;|&nbsp; {{ clause.explanation }}</small>
</div>
{% endif %}
{% endfor %}
{% endif %}

{% if scan.cv_results %}
<h2>UI Pattern Analysis</h2>
<table>
  <tr><th>Pattern</th><th>Confidence</th><th>Severity</th><th>Description</th></tr>
  {% for pattern in scan.cv_results %}
  <tr>
    <td>{{ pattern.label }}</td>
    <td>{{ "%.1f%%"|format(pattern.confidence * 100) }}</td>
    <td>{{ "%.2f"|format(pattern.severity) }}</td>
    <td>{{ pattern.description }}</td>
  </tr>
  {% endfor %}
</table>
{% endif %}

<p class="meta" style="margin-top:40px;">Generated by Dark Pattern Detector &mdash; {{ now }}</p>
</body>
</html>
"""


async def generate_pdf_report(scan: "ScanResult") -> bytes:  # noqa: F821
    """Render a scan result as a PDF report.

    Args:
        scan: ScanResult document retrieved from MongoDB.

    Returns:
        Raw PDF bytes.
    """
    try:
        from weasyprint import HTML

        if _jinja_env:
            template = _jinja_env.get_template("report.html")
        else:
            from jinja2 import Template
            template = Template(_INLINE_TEMPLATE)

        html_content = template.render(scan=scan, now=datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC"))
        pdf_bytes = HTML(string=html_content).write_pdf()
        logger.info("PDF generated", scan_id=scan.scan_id, bytes=len(pdf_bytes))
        return pdf_bytes
    except ImportError:
        logger.error("WeasyPrint not installed — returning HTML fallback")
        raise RuntimeError("WeasyPrint is not available. Install it with: pip install weasyprint")
